---
micronaut:
  application:
    name: bazel-micronaut-example
  server:
    host: 0.0.0.0
    port: 9980
  http:
    client:
      read-timeout: 2s
---
jackson:
  serialization:
    writeDatesAsTimestamps: true
